# Generated by Django 2.2.4 on 2019-09-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('card_set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clan', models.IntegerField()),
                ('card_name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('card_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='index.Expansion')),
            ],
        ),
    ]
